---

- name: ensure that Git is installed
  yum: name={{ item }} state=latest
  with_items:
  - git

- name: Make sure virk doesn't already exist
  stat:
    path: "{{ VIRK_DIR }}"
  register: stat_result
  
- name: clone virk
  vars:
    VERSION: "{{ VIYA_VERSION }}"
  git:
    repo: "{{ VIRK_URL }}"
    dest: "{{ VIRK_DIR }}"
    version: "{{VIRK_COMMIT_ID[VERSION]}}"
    force: yes
  when: state_result.stat.exists == False
