---

- name: Perform common tasks on all machines
  hosts: openldapall
  module_defaults:
    yum:
      lock_timeout: 300
  become: yes
  become_user: root
  roles:
    - role: openldap/openldapcommon
  tags:
    - openldapcommon

- name: Install OpenLDAP Server on a single machine
  hosts: OpenLdapServer
  module_defaults:
    yum:
      lock_timeout: 300
  become: yes
  become_user: root
  roles:
    - role: openldap/openldapserver
  tags:
    - openldapserver

- name: Install KDC/LDAP Client on one or more machines
  hosts: OpenLdapClients
  module_defaults:
    yum:
      lock_timeout: 300
  become: yes
  become_user: root
  roles:
     - role: openldap/openldapclients
  tags:
     - openldapclients
